// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQu25ELfUUziMncDCZlh7rDxUOyGuRHGA',
    appId: '1:397121791649:web:d24a88737e1f4ae662f2e0',
    messagingSenderId: '397121791649',
    projectId: 'nob-d0c2f',
    authDomain: 'nob-d0c2f.firebaseapp.com',
    storageBucket: 'nob-d0c2f.appspot.com',
    measurementId: 'G-4YDC6J71C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIKo_LgOS8xLcUkWTtM2AUtP7kVL5QzvQ',
    appId: '1:397121791649:android:8a238c7aae88eeb362f2e0',
    messagingSenderId: '397121791649',
    projectId: 'nob-d0c2f',
    storageBucket: 'nob-d0c2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwSMZgFLYVPmgjA8l3g0m34Rd5ROCtRew',
    appId: '1:397121791649:ios:876ba6c2e9afd33362f2e0',
    messagingSenderId: '397121791649',
    projectId: 'nob-d0c2f',
    storageBucket: 'nob-d0c2f.appspot.com',
    iosClientId: '397121791649-r0h4kuvghbcrdvo6tsnr68aldd3l64jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwSMZgFLYVPmgjA8l3g0m34Rd5ROCtRew',
    appId: '1:397121791649:ios:7a3832b7a6da118962f2e0',
    messagingSenderId: '397121791649',
    projectId: 'nob-d0c2f',
    storageBucket: 'nob-d0c2f.appspot.com',
    iosClientId: '397121791649-4lit3ah00qh96ur9csv1nvge9grumbc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.nob.RunnerTests',
  );
}
